---
kind: pipeline
name: linux-amd64
platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
    - tag

steps:
- name: build
  image: niusmallnan/hardened-build-base:v1.17.11n1
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - make image-build
  when:
    event:
    - tag
    ref:
    - refs/tags/*

- name: scan
  image: niusmallnan/hardened-build-base:v1.17.11n1
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - TAG=${DRONE_TAG} make image-scan
  when:
    event:
    - tag
    ref:
    - refs/tags/*

- name: publish
  image: niusmallnan/hardened-build-base:v1.17.11n1
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag
    ref:
    - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

node:
  instance: agent-amd64

---
kind: pipeline
name: linux-arm64
platform:
  os: linux
  arch: arm64

trigger:
  event:
    include:
    - tag

steps:
- name: build
  image: niusmallnan/hardened-build-base:v1.17.11n1
  failure: ignore
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - make image-build
  when:
    event:
    - tag
    ref:
    - refs/tags/*

- name: publish
  image: niusmallnan/hardened-build-base:v1.17.11n1
  failure: ignore
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    event:
    - tag
    ref:
    - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

node:
  instance: agent-arm64

---
kind: pipeline
type: docker
name: manifest
platform:
  os: linux
  arch: amd64
steps:
- name: push
  image: plugins/manifest:1.2.3
  settings:
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    spec: manifest.tmpl
    ignore_missing: true
  when:
    event:
    - tag
depends_on:
- linux-amd64
- linux-arm64

trigger:
  event:
    include:
    - tag

node:
  instance: agent-amd64
...
